#!/usr/bin/env python3
"""Assemble design/ui-overhaul/chic-style-board.html from its parts.

WHY A GENERATOR AND NOT A HAND-WRITTEN PAGE
    The board has to be ONE self-contained file. The owner opens it from disk, and the previous
    board (design/ui-overhaul/style-board.html) pulls its five fonts from Google over the network
    -- so it renders in a different typeface for anyone reading it offline, which is the one thing
    a font board must not do. Everything here is inlined instead: glyph-subsetted woff2 as base64,
    the town backdrop as a data URI, and the minimap as real geometry.

    The minimap in particular is not a drawing. It is generated from
    public/act1-hifi/town/portSapphire-walkable.json -- the same polygon set the game collides
    against -- plus the shop / save / NPC / exit cells from the town config. What the owner judges
    is the actual minimap under each palette.

PARTS (design/ui-overhaul/chic-board/)
    fonts.css     base64 @font-face blocks; regenerate with scripts/fetch_style_board_fonts.py
    style.css     board chrome + one block per direction
    body.html     markup and the direction list
    backdrop.jpg  a real Port Sapphire frame, behind the field-HUD strip

    python3 scripts/build_chic_style_board.py
"""
from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = ROOT / "design" / "ui-overhaul" / "chic-board"
OUT = ROOT / "design" / "ui-overhaul" / "chic-style-board.html"
WALKABLE = ROOT / "public" / "act1-hifi" / "town" / "portSapphire-walkable.json"
TOWN = ROOT / "public" / "act1-hifi" / "town" / "portSapphire-town.json"


def minimap_svg() -> str:
    """The real town, in a 0..100 viewBox so the CSS can size it freely."""
    walk = json.loads(WALKABLE.read_text(encoding="utf-8"))
    town = json.loads(TOWN.read_text(encoding="utf-8"))
    scale = 100.0 / walk["coordinateSpace"]["width"]

    def path(points) -> str:
        return "M" + " ".join(f'{p["x"]*scale:.2f},{p["y"]*scale:.2f}' for p in points) + "Z"

    # Outer ring and its holes share one path so fill-rule=evenodd punches the holes out.
    ground = "".join(
        path(r["outer"]) + "".join(path(h) for h in r.get("holes", []))
        for r in walk["regions"]
    )
    props = "".join(path(o["polygon"]) for o in walk["staticObstacles"])

    cell = town["worldPxPerCell"] * scale

    def dot(c, css_class: str, r: float) -> str:
        if not c:
            return ""
        return f'<circle cx="{c[0]*cell:.2f}" cy="{c[1]*cell:.2f}" r="{r}" class="{css_class}"/>'

    poi = "".join(dot(n["cell"], "poi-npc", 1.6) for n in town["npcs"])
    poi += dot(town.get("shopCounter"), "poi-shop", 2.0)
    poi += dot(town.get("savePoint"), "poi-save", 2.0)
    poi += dot(town["exit"]["cell"], "poi-exit", 2.2)
    hero = town["startCell"]
    poi += (f'<rect x="{hero[0]*cell-1.4:.2f}" y="{hero[1]*cell-1.4:.2f}" '
            f'width="2.8" height="2.8" class="poi-hero"/>')

    return ('<svg viewBox="0 0 100 100">'
            '<rect x="0" y="0" width="100" height="100" class="mini-bg"/>'
            f'<path class="mini-ground" fill-rule="evenodd" d="{ground}"/>'
            f'<path class="mini-prop" d="{props}"/>'
            f"{poi}</svg>")


def main() -> int:
    for part in ("fonts.css", "style.css", "body.html", "backdrop.jpg"):
        if not (PARTS / part).is_file():
            sys.exit(f"missing board part: {PARTS / part}")

    body = (PARTS / "body.html").read_text(encoding="utf-8")
    if "<!--MINIMAP-->" not in body:
        sys.exit("body.html has no <!--MINIMAP--> slot to fill")
    body = body.replace("<!--MINIMAP-->", minimap_svg())

    backdrop = base64.b64encode((PARTS / "backdrop.jpg").read_bytes()).decode("ascii")

    OUT.write_text(
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="UTF-8" />\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        "<title>Quest of Knowledge — chic directions (font + palette)</title>\n"
        "<style>\n"
        "/* GENERATED by scripts/build_chic_style_board.py -- edit design/ui-overhaul/chic-board/,\n"
        "   not this file. Fonts are glyph-subsetted woff2 inlined as base64, so the page needs no\n"
        "   network and renders in the intended typeface offline. */\n"
        + (PARTS / "fonts.css").read_text(encoding="utf-8")
        + f':root {{ --townimg: url("data:image/jpeg;base64,{backdrop}"); }}\n'
        + (PARTS / "style.css").read_text(encoding="utf-8")
        + "</style>\n</head>\n<body>\n"
        + body
        + "</body>\n</html>\n",
        encoding="utf-8",
    )
    print(f"WROTE {OUT.relative_to(ROOT)}  {OUT.stat().st_size:,} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
