#!/usr/bin/env python3
"""Ship the Act 1 landmark sprites to the runtime, with their measured ground anchors.

WHY THIS EXISTS
    CODEX-ART-BRIEF-V7: "Landmarks are composited at runtime as sprites (owner decision
    2026-07-30). Bases carry only the site: a bare packed-earth pad and worn approach."
    So a landmark-free terrain bake is CORRECT -- the r26 chunks are right. What was missing
    is the other half: nothing ever shipped the sprites or drew them, so the hi-fi overworld
    renders bare earth pads where every town and dungeon should stand. Owner, 2026-08-03:
    "the current in game designs completely ignore the special assets we generated recently."

THE ANCHOR IS MEASURED, NOT GUESSED
    scripts/key_landmark_sprite.footprint() finds where the sprite MEETS THE GROUND: the
    widest band of its silhouette, which for an isometric diorama is the base ellipse. The
    owner had already caught the alternative failing -- "the assets don't look like they are
    floating and the patch underneath the town is in the wrong place" -- which happened when
    the sprite was anchored at a hardcoded 80% down the canvas while the terrain's earth pad
    was centred on the landmark cell. This reuses the SAME function render_material_map.py
    uses to size the pad, so the clearing and the thing standing in it cannot disagree.

    Sizes come from render_material_map.py too: 192 px for the three towns, 144 px otherwise.

OUTPUT
    public/act1-hifi/landmarks/<slug>.png   the sprite at its final rendered size
    public/act1-hifi/landmarks/landmarks.json  cell, size and measured anchor per landmark

Read-only on owner-terrain.json and landmark-sprites/ -- both are owner input.
"""
from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OWNER = ROOT / "design/continent-terrain-class-method/owner-terrain"
SPRITES = OWNER / "landmark-sprites"
OUT = ROOT / "public/act1-hifi/landmarks"
ACT = "1"
PX = 48                                   # world px per cell, matching the r26 bake
TOWN_NAMES = {"Greenhollow", "Millbrook", "Port Sapphire"}


def load_footprint():
    spec = importlib.util.spec_from_file_location(
        "kls", str(ROOT / "scripts/key_landmark_sprite.py"))
    kls = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(kls)
    return kls.footprint


def main() -> int:
    footprint = load_footprint()
    act = json.loads((OWNER / "owner-terrain.json").read_text())["acts"][ACT]
    x0, y0 = act["bounds"][0], act["bounds"][1]
    OUT.mkdir(parents=True, exist_ok=True)

    entries, missing = [], []
    for name, (cx, cy) in sorted(act["landmarks"].items()):
        slug = name.lower().replace(" ", "-")
        src = SPRITES / f"{slug}.png"
        if not src.is_file():
            missing.append(name)
            continue
        size = 192 if name in TOWN_NAMES else 144
        sp = Image.open(src).convert("RGBA")
        if sp.size != (size, size):
            sp = sp.resize((size, size), Image.LANCZOS)
        fx, fy, wmax, band = footprint(sp)
        sp.save(OUT / f"{slug}.png")
        entries.append({
            "name": name, "slug": slug, "cell": [cx, cy],
            # plate-local cell, so a runtime that only knows the Act 1 window can place it
            "plateCell": [cx - x0, cy - y0],
            "size": size,
            # where the sprite meets the ground, in sprite pixels. Draw so this pixel lands on
            # the landmark cell's centre -- never the sprite's own centre or its bottom edge.
            "anchor": [fx, fy],
            "contactWidth": wmax, "contactBand": band,
        })

    if missing:
        raise SystemExit(f"landmarks with no sprite on disk: {missing} -- refusing to ship a "
                         f"partial set, since a silently absent landmark is invisible in game")
    if not entries:
        raise SystemExit("no landmarks resolved -- owner-terrain.json changed shape?")

    manifest = {
        "_comment": ("Act 1 landmark sprites for RUNTIME compositing, per CODEX-ART-BRIEF-V7 "
                     "('landmarks are composited at runtime as sprites'). Draw each sprite so "
                     "its `anchor` pixel sits on the centre of `cell`; the terrain bake already "
                     "carries the matching packed-earth pad at that cell. Generated by "
                     "scripts/build_act1_landmark_runtime.py -- do not hand-edit."),
        "worldPxPerCell": PX,
        "act": int(ACT),
        "bounds": act["bounds"],
        "landmarks": entries,
    }
    (OUT / "landmarks.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"ACT 1 LANDMARK RUNTIME: {len(entries)} sprites -> {OUT.relative_to(ROOT)}")
    for e in entries:
        print(f"  {e['name']:16s} cell {e['cell'][0]:3d},{e['cell'][1]:3d}  "
              f"{e['size']}px  anchor {e['anchor'][0]:3d},{e['anchor'][1]:3d}  "
              f"contact {e['contactWidth']}x{e['contactBand']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
