#!/usr/bin/env node
//
// Writes public/act1-world-map.js + dist/act1-world-map.js -- the Act-1 overworld override the
// shipped bundle runs against.
//
// SOURCE CHANGED 2026-08-03 (owner direction): the plate is now built from the OWNER'S PAINTED
// TERRAIN (scripts/act1_owner_paint_plate.mjs), not from buildAct1OverworldReconstruction() plus a
// snapshot of the already-shipped runtime. Those two inputs produced the generated semantic map
// the owner rejected on 29 Jul, and kept the collision at 53.1% agreement with the paint the art
// had already moved to. `ACT1_V3_LOCKED_DESIGN_SHA256` locked THAT design and is deliberately no
// longer asserted here; provenance is now a hash of the owner's own inputs (plate.sourceSha256).
//
// The override does four things to the base scene, all reversible monkey-patches on the live
// WorldMapScene -- no bundle edit, no build:
//   1. apply()             rewrites scene.mapData inside the Act-1 rectangle to the plate
//   2. canMove             additionally blocks forest (tile 3), which the base game walks through
//   3. checkTransition     fires the eight Act-1 doors at the OWNER'S coordinates, both ways
//   4. getCompassTarget    aims the quest compass at the owner's coordinates
//
// SINGLE ENTRANCE, 2026-08-18 (owner): "only one entrance for towns and dungeons (unless they
// connect acts or in other special circumstances) and the edge need to be blockers so the user
// cannot walk on top of it." The plate the builder hands over still calls the ground under every
// landmark SPRITE plain grass, so the player walked over the drawn palisade and reached each door
// from all four sides. `act1_landmark_footprints.mjs` runs as a post-pass over the plate and
// stamps those cells unwalkable, leaving the door and ONE gateway cell -- so the collision now
// carries the art's own silhouette rather than a single 48 px door in an open field.
//
// (3) is required, not optional. The bundle's connection table is frozen at the generated layout
// (Greenhollow 60,340 / Millbrook 100,320 / Misty Grotto 120,260 ...) and its overworld branch only
// accepts a connection within Manhattan distance 3 of the cell stepped into, so moving the doors
// without moving the trigger would brick every Act-1 destination.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildAct1OwnerPaintPlate, validatePlate } from './act1_owner_paint_plate.mjs';
import { applyLandmarkFootprints } from './act1_landmark_footprints.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUTS = [
  resolve(ROOT, 'public/act1-world-map.js'),
  resolve(ROOT, 'dist/act1-world-map.js'),
];

const assert = (condition, message) => { if (!condition) throw new Error(message); };
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');

function renderRuntimeOverride(plate) {
  const rows = plate.rows.map(row => `    '${row}',`).join('\n');
  const entries = plate.landmarks.map(landmark => ({
    mapId: landmark.mapId,
    at: landmark.at,
    tile: landmark.tile,
    toX: landmark.enter.toX,
    toY: landmark.enter.toY,
    exit: landmark.exit,
  }));
  return `// Generated by scripts/export_act1_runtime_override.mjs. Do not edit.\n`
    + `// Collision source: the OWNER'S PAINTED TERRAIN -- owner-terrain.json acts.1.terrainRows\n`
    + `// composited with continent-macro-g3/land-mask.npy, the same rule build_owner_semantic_maps.py\n`
    + `// uses for the art. Owner source SHA-256: ${plate.sourceSha256}\n`
    + `(function () {\n`
    + `  'use strict';\n`
    + `  var REVISION = 7;\n`
    + `  var SOURCE_SHA256 = '${plate.sourceSha256}';\n`
    + `  var PLATE_SHA256 = '${plate.plateSha256}';\n`
    + `  var BOUNDS = ${JSON.stringify(plate.bounds)};\n`
    + `  var ROWS = [\n${rows}\n  ];\n`
    + `  // The eight Act-1 destinations at the owner's placement. 'at' is the door cell (blocked,\n`
    + `  // and stepping into it transitions); 'toX/toY' is the arrival cell inside the destination,\n`
    + `  // lifted verbatim from the bundle; 'exit' is where the hero lands coming back out.\n`
    + `  var LANDMARKS = ${JSON.stringify(entries)};\n`
    + `  var SAFE = ${JSON.stringify(plate.safeCandidates)};\n`
    + `  var FOREST_BLOCK = ${JSON.stringify(plate.forestBlock)};\n`
    + `  var BRIDGE_DECKS = ${JSON.stringify(plate.bridgeDecks)};\n`
    + `  var HARBOR_CELLS = ${JSON.stringify(plate.harborCells)};\n`
    + `  var GATE = ${JSON.stringify(plate.gate)};\n`
    + `  // Every cell the landmark SPRITES cover closely enough to hide the hero inside, stamped\n`
    + `  // unwalkable so she cannot walk on top of the drawn town or cave. Derived from each\n`
    + `  // sprite's own alpha eroded by her 12 px contact disc -- scripts/act1_landmark_footprints.mjs.\n`
    + `  // Exposed for verification only; the collision itself is already in ROWS.\n`
    + `  var LANDMARK_BLOCKERS = ${JSON.stringify(plate.landmarkBlockers)};\n`
    + `  var state = { appliedMap: null, relocation: null, wrappedScene: null, repairs: 0 };\n`
    + `  var ENTRY = {}, EXITS = {}, COMPASS = {};\n`
    + `  for (var li = 0; li < LANDMARKS.length; li++) { var L = LANDMARKS[li];\n`
    + `    ENTRY[L.at.x + ',' + L.at.y] = L; EXITS[L.mapId] = L.exit; COMPASS[L.mapId] = L.at; }\n`
    + `  // ROWS decoded once. Everything below reads TILES, so the plate write and the integrity\n`
    + `  // sweep are plain integer compares rather than 27k parseInt calls a tick.\n`
    + `  var TILES = [];\n`
    + `  for (var ti = 0; ti < ROWS.length; ti++) { var trow = ROWS[ti], tout = [];\n`
    + `    for (var tj = 0; tj < trow.length; tj++) tout.push(parseInt(trow.charAt(tj),36));\n`
    + `    TILES.push(tout); }\n`
    + `  function inside(x,y){ return x>=BOUNDS[0]&&x<=BOUNDS[2]&&y>=BOUNDS[1]&&y<=BOUNDS[3]; }\n`
    + `  function tileAt(x,y){ return TILES[y-BOUNDS[1]][x-BOUNDS[0]]; }\n`
    + `  function blocked(tile){ return tile===2||tile===3||tile===4||tile>=6; }\n`
    + `  function gateOpen(){ var gs=window.__GAME_STATE__,flags=gs&&gs.player&&gs.player.state&&gs.player.state.storyFlags; return !!(flags&&flags[GATE.requiredFlag]); }\n`
    + `  function gateRestricted(x,y){ if(gateOpen()) return false; for(var i=0;i<GATE.closedSide.length;i++){var p=GATE.closedSide[i];if(p.x===x&&p.y===y)return true;} return false; }\n`
    + `  function wrapCanMove(scene){\n`
    + `    if(scene.__act1CanMoveWrapped||typeof scene.canMove!=='function') return;\n`
    + `    var original=scene.canMove;\n`
    + `    scene.canMove=function(x,y){\n`
    + `      ensurePlate(this,false);\n`
    + `      if(this.currentMapId==='overworld'&&state.appliedMap===this.mapData&&inside(x,y)&&(tileAt(x,y)===3||gateRestricted(x,y))) return false;\n`
    + `      return original.call(this,x,y);\n`
    + `    };\n`
    + `    scene.__act1CanMoveWrapped=true;\n`
    + `  }\n`
    + `  // The bundle's overworld branch matches the nearest connection within Manhattan 3 of the\n`
    + `  // cell stepped into, and that table is frozen at the generated layout. Intercept the eight\n`
    + `  // Act-1 doors on the way in; on the way out, rewrite any base result that would land the\n`
    + `  // hero inside the Act-1 rectangle (which is exactly the Act-1 half of every connection --\n`
    + `  // Crystal Cave's OTHER mouth at 172,306 is outside the bounds and is left alone).\n`
    + `  function wrapCheckTransition(scene){\n`
    + `    if(scene.__act1TransitionWrapped||typeof scene.checkTransition!=='function') return;\n`
    + `    var original=scene.checkTransition;\n`
    + `    scene.checkTransition=function(x,y){\n`
    + `      ensurePlate(this,false);\n`
    + `      if(this.currentMapId==='overworld'&&state.appliedMap===this.mapData&&inside(x,y)){\n`
    + `        if(this.transitionCooldown>0){ this.transitionCooldown--; return null; }\n`
    + `        var hit=ENTRY[x+','+y];\n`
    + `        if(hit) return { targetMap:hit.mapId, toX:hit.toX, toY:hit.toY };\n`
    + `      }\n`
    + `      var result=original.call(this,x,y);\n`
    + `      if(result&&result.targetMap==='overworld'&&inside(result.toX,result.toY)){\n`
    + `        var out=EXITS[this.currentMapId];\n`
    + `        if(out){ result.toX=out.x; result.toY=out.y; }\n`
    + `      }\n`
    + `      return result;\n`
    + `    };\n`
    + `    scene.__act1TransitionWrapped=true;\n`
    + `  }\n`
    + `  // The quest compass reads a frozen ox/oy table too, so without this it points at open sea.\n`
    + `  function wrapCompass(scene){\n`
    + `    if(scene.__act1CompassWrapped||typeof scene.getCompassTarget!=='function') return;\n`
    + `    var original=scene.getCompassTarget;\n`
    + `    scene.getCompassTarget=function(){\n`
    + `      var target=original.call(this);\n`
    + `      if(!target) return target;\n`
    + `      var moved=COMPASS[target.mapId];\n`
    + `      if(!moved) return target;\n`
    + `      var copy={}; for(var k in target) if(Object.prototype.hasOwnProperty.call(target,k)) copy[k]=target[k];\n`
    + `      copy.ox=moved.x; copy.oy=moved.y; return copy;\n`
    + `    };\n`
    + `    scene.__act1CompassWrapped=true;\n`
    + `  }\n`
    + `  function wrapScene(scene){\n`
    + `    if(!scene) return false;\n`
    + `    wrapCanMove(scene); wrapCheckTransition(scene); wrapCompass(scene);\n`
    + `    state.wrappedScene=scene; return true;\n`
    + `  }\n`
    + `  // apply() only ever runs once the hero is ALREADY on the overworld, but a new game starts\n`
    + `  // inside Greenhollow and the very first thing it does is walk out -- an exit that has to be\n`
    + `  // remapped before the overworld has been seen. So the wrappers arm themselves off the live\n`
    + `  // scene instead, and re-arm if the scene is ever rebuilt.\n`
    + `  function findScene(){\n`
    + `    var gs=window.__GAME_STATE__, game=window.__PHASER_GAME__||(gs&&gs.game);\n`
    + `    return (game&&game.scene&&typeof game.scene.getScene==='function') ? game.scene.getScene('WorldMapScene') : null;\n`
    + `  }\n`
    + `  function armWrappers(){ try{ var s=findScene(); wrapScene(s); ensurePlate(s,true); }catch(e){} }\n`
    + `  armWrappers();\n`
    + `  var armTimer=(typeof window.setInterval==='function')?window.setInterval(armWrappers, 400):null;\n`
    + `  function relocateIfNeeded(scene){\n`
    + `    var x=scene.heroTileX,y=scene.heroTileY;\n`
    + `    if(!inside(x,y)||(!blocked(scene.mapData[y][x])&&!gateRestricted(x,y))) return null;\n`
    + `    var best=null,bestD=Infinity;\n`
    + `    for(var i=0;i<SAFE.length;i++){ var p=SAFE[i],t=scene.mapData[p.y][p.x]; if(blocked(t)||gateRestricted(p.x,p.y)) continue;\n`
    + `      var d=Math.abs(p.x-x)+Math.abs(p.y-y); if(d<bestD){best=p;bestD=d;} }\n`
    + `    if(!best) throw new Error('Act 1 override has no safe relocation candidate');\n`
    + `    scene.heroTileX=best.x; scene.heroTileY=best.y;\n`
    + `    var sprite=scene.hero,first=scene.tileGrid&&scene.tileGrid[0]&&scene.tileGrid[0][0];\n`
    + `    var size=(first&&first.displayWidth)||48; if(sprite){sprite.x=best.x*size+size/2;sprite.y=best.y*size+size/2;}\n`
    + `    if(typeof scene.updatePosition==='function') scene.updatePosition();\n`
    + `    if(typeof scene.updateCamera==='function') scene.updateCamera();\n`
    + `    return {from:{x:x,y:y},to:{x:best.x,y:best.y}};\n`
    + `  }\n`
    + `  function usable(scene){\n`
    + `    return !!(scene&&scene.currentMapId==='overworld'&&scene.mapData&&scene.mapData.length===400\n`
    + `      &&scene.mapData[0]&&scene.mapData[0].length===320);\n`
    + `  }\n`
    + `  function writePlate(scene){\n`
    + `    for(var ry=0;ry<TILES.length;ry++){ var row=TILES[ry],target=scene.mapData[BOUNDS[1]+ry];\n`
    + `      for(var rx=0;rx<row.length;rx++) target[BOUNDS[0]+rx]=row[rx]; }\n`
    + `  }\n`
    + `  function plateIntact(scene){\n`
    + `    for(var ry=0;ry<TILES.length;ry++){ var row=TILES[ry],target=scene.mapData[BOUNDS[1]+ry];\n`
    + `      if(!target) return false;\n`
    + `      for(var rx=0;rx<row.length;rx++) if(target[BOUNDS[0]+rx]!==row[rx]) return false; }\n`
    + `    return true;\n`
    + `  }\n`
    + `  // Leaving a town hands the overworld a BRAND NEW mapData array, and the reskin path that\n`
    + `  // calls apply() is gated on mapId+dimensions -- an identical string -- so it skips the\n`
    + `  // re-apply entirely and every Act-1 door reverts to the base generator's. That was survivable\n`
    + `  // while the plate merely echoed the generated map; against the owner's paint it deletes all\n`
    + `  // eight destinations, so the override no longer waits to be called.\n`
    + `  //   shallow: the array changed -> full apply, hero relocated if the paint moved the ground\n`
    + `  //            under a retained position. Cheap enough for the movement path.\n`
    + `  //   deep:    the array is the same one but something wrote into it (the reskin pass\n`
    + `  //            consolidates mountains in place) -> rewrite the rect, leave the hero alone.\n`
    + `  var applying=false;\n`
    + `  function ensurePlate(scene,deep){\n`
    + `    if(applying||!usable(scene)) return false;\n`
    + `    applying=true;\n`
    + `    try{\n`
    + `      if(state.appliedMap!==scene.mapData){\n`
    + `        writePlate(scene); state.appliedMap=scene.mapData; state.relocation=relocateIfNeeded(scene);\n`
    + `        return true;\n`
    + `      }\n`
    + `      if(deep&&!plateIntact(scene)){ writePlate(scene); state.repairs++; return true; }\n`
    + `      return false;\n`
    + `    } finally { applying=false; }\n`
    + `  }\n`
    + `  function apply(scene){\n`
    + `    if(!usable(scene)) return false;\n`
    + `    wrapScene(scene);\n`
    + `    return ensurePlate(scene,true);\n`
    + `  }\n`
    + `  window.__ACT1_WORLD_MAP__={ revision:REVISION, sourceSha256:SOURCE_SHA256, plateSha256:PLATE_SHA256, bounds:BOUNDS.slice(), landmarks:LANDMARKS, forestBlock:FOREST_BLOCK, bridgeDecks:BRIDGE_DECKS, harborCells:HARBOR_CELLS, gate:GATE, landmarkBlockers:LANDMARK_BLOCKERS, apply:apply, ensurePlate:ensurePlate, armWrappers:armWrappers, armTimer:armTimer, state:state };\n`
    + `})();\n`;
}

const args = process.argv.slice(2);
assert(args.length <= 1 && (args.length === 0 || args[0] === '--check'), 'usage: export_act1_runtime_override.mjs [--check]');
const plate = buildAct1OwnerPaintPlate();
// THE SINGLE-ENTRANCE POST-PASS. The owner's plate places the doors; this stamps the sprite
// footprints around them so each landmark has exactly one way in and no walkable roof. It runs
// BEFORE validatePlate deliberately -- the connectivity, reachability and no-leak assertions there
// are the proof that blocking did not strand anything, and re-using them beats writing a second,
// weaker copy here.
const footprints = applyLandmarkFootprints(plate);
const stats = validatePlate(plate);
const content = renderRuntimeOverride(plate);

if (args[0] === '--check') {
  for (const output of OUTPUTS) assert(readFileSync(output, 'utf8') === content, `${output} is stale`);
  console.log(`ACT 1 RUNTIME OVERRIDE CHECK PASS: ${sha256(content)}`
    + ` (${stats.landmarks} owner-placed landmarks, ${stats.regionCells}-cell single walkable region,`
    + ` ${plate.landmarkBlockers.length} landmark blocker cells)`);
} else {
  for (const output of OUTPUTS) writeFileSync(output, content);
  console.log(`ACT 1 RUNTIME OVERRIDE WRITTEN: ${sha256(content)}`
    + ` (${stats.landmarks} owner-placed landmarks, ${stats.regionCells}-cell single walkable region,`
    + ` ${plate.landmarkBlockers.length} landmark blocker cells)`);
  for (const entry of footprints.landmarks) {
    console.log(`  ${entry.mapId.padEnd(20)} ${entry.skipped
      ? `SKIPPED (${entry.skipped})`
      : `${String(entry.blocked).padStart(2)} of ${String(entry.footprint).padStart(2)} footprint cells blocked;`
        + ` one entrance from the ${entry.approach} at ${entry.gateway.x},${entry.gateway.y}`}`);
  }
  if (footprints.undrawn.length) {
    console.log(`  sprites with no door, never drawn, not blocked: ${footprints.undrawn.join(', ')}`);
  }
}
