#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/map-engine/generated/act1RuntimeSnapshot.ts');
const BUNDLE_PATH = resolve(ROOT, 'dist/assets/index-BhoGQRaA.js');
const PUBLIC_DQ_PATH = resolve(ROOT, 'public/dq-tiles.js');
const DIST_DQ_PATH = resolve(ROOT, 'dist/dq-tiles.js');

const BUNDLE_SHA256 = 'a56026574b42168985b353e4cee824562716af83f92d03f408df04eac9127381';
const DQ_TILES_SHA256 = 'a4ecf27974402e857478a85c1f2396777ba3b92cbcb5a8b19555cd99af4c0055';
const PRE_OVERRIDE_MAP_SHA256 = '97f0b936946695b5ce2eb073df4b9905e680942b299a5f87f1bf5c0544b96723';
const FINAL_MAP_SHA256 = '2d82e050b51095280b74395db8656aed52ae919206385827502265f6e0a65202';
const MAP_WIDTH = 320;
const MAP_HEIGHT = 400;
const ACT1_START = [60, 341];
const ACT1_BOUNDS = [16, 218, 163, 399];
const ACT1_WIDTH = 148;
const ACT1_HEIGHT = 182;

const sha256 = value => createHash('sha256').update(value).digest('hex');
const assert = (condition, message) => { if (!condition) throw new Error(message); };

function extractRawTerrain(bundle) {
  const helper = bundle.indexOf('function Js(n)');
  const generator = bundle.indexOf('function Ep(n, x) {');
  const path = bundle.indexOf('\nfunction ', generator + 20);
  const afterPath = bundle.indexOf('\nfunction ', path + 20);
  assert(helper >= 0 && generator >= 0 && path >= 0 && afterPath >= 0, 'bundle generator slices missing');
  const code = bundle.slice(helper, generator) + bundle.slice(generator, path) + bundle.slice(path, afterPath);
  return Function(`"use strict"; const Gr=[]; ${code}; return Ep(${MAP_WIDTH},${MAP_HEIGHT});`)();
}

function extractConsolidator(dqTiles) {
  const start = dqTiles.indexOf('var MIN_KEEP=6');
  const end = dqTiles.indexOf('function inRM(', start);
  assert(start >= 0 && end > start, 'dq consolidator slice missing');
  return Function('window', `${dqTiles.slice(start, end)}; return consolidateMapData;`)({});
}

function assertMapDimensions(map, label) {
  assert(Array.isArray(map) && map.length === MAP_HEIGHT, `${label} height must be ${MAP_HEIGHT}`);
  assert(map.every(row => Array.isArray(row) && row.length === MAP_WIDTH), `${label} width must be ${MAP_WIDTH}`);
}

function extractAct1Rows(map) {
  const [minX, minY, maxX, maxY] = ACT1_BOUNDS;
  assert(maxX - minX + 1 === ACT1_WIDTH, `Act 1 width must be ${ACT1_WIDTH}`);
  assert(maxY - minY + 1 === ACT1_HEIGHT, `Act 1 height must be ${ACT1_HEIGHT}`);

  const bytes = [];
  const rows = [];
  for (let y = minY; y <= maxY; y += 1) {
    let row = '';
    for (let x = minX; x <= maxX; x += 1) {
      const tile = map[y][x];
      assert(Number.isInteger(tile) && tile >= 0 && tile < 36, `tile ${x},${y} cannot use one-digit base36`);
      bytes.push(tile);
      row += tile.toString(36);
    }
    assert(row.length === ACT1_WIDTH, `Act 1 row ${y} width mismatch`);
    rows.push(row);
  }
  assert(rows.length === ACT1_HEIGHT, 'Act 1 row count mismatch');
  return { rows, sha256: sha256(Buffer.from(bytes)) };
}

function renderSnapshot(rows, plateSha256) {
  const encodedRows = rows.map(row => `  '${row}',`).join('\n');
  return `// Generated by scripts/extract_act1_runtime_snapshot.mjs. Do not edit.\n\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_SCHEMA_VERSION = 1;\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_ENCODING = 'one lowercase base36 digit per runtime tile; rows north-to-south, columns west-to-east';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_BUNDLE_SHA256 = '${BUNDLE_SHA256}';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_DQ_TILES_SHA256 = '${DQ_TILES_SHA256}';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_PRE_OVERRIDE_MAP_SHA256 = '${PRE_OVERRIDE_MAP_SHA256}';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_FINAL_MAP_SHA256 = '${FINAL_MAP_SHA256}';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_PLATE_SHA256 = '${plateSha256}';\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_WORLD_SIZE = [${MAP_WIDTH}, ${MAP_HEIGHT}] as const;\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_START = [${ACT1_START.join(', ')}] as const;\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_BOUNDS = [${ACT1_BOUNDS.join(', ')}] as const;\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_SIZE = [${ACT1_WIDTH}, ${ACT1_HEIGHT}] as const;\n`
    + `export const ACT1_RUNTIME_SNAPSHOT_ROWS = [\n${encodedRows}\n] as const;\n`;
}

function generateSnapshot() {
  const bundleBytes = readFileSync(BUNDLE_PATH);
  const publicDqBytes = readFileSync(PUBLIC_DQ_PATH);
  const distDqBytes = readFileSync(DIST_DQ_PATH);
  assert(sha256(bundleBytes) === BUNDLE_SHA256, 'bundle hash mismatch');
  assert(publicDqBytes.equals(distDqBytes), 'public/dist dq-tiles twins differ');
  assert(sha256(publicDqBytes) === DQ_TILES_SHA256, 'dq-tiles hash mismatch');

  const raw = extractRawTerrain(bundleBytes.toString('utf8'));
  assertMapDimensions(raw, 'pre-override map');
  assert(sha256(Buffer.from(raw.flat())) === PRE_OVERRIDE_MAP_SHA256, 'pre-override generator hash mismatch');

  const map = raw.map(row => row.slice());
  const stats = extractConsolidator(publicDqBytes.toString('utf8'))({
    mapData: map,
    heroTileX: ACT1_START[0],
    heroTileY: ACT1_START[1],
  });
  assertMapDimensions(map, 'post-dq map');
  assert(stats.safe, 'Act 1 dq safety gate failed');
  assert(sha256(Buffer.from(map.flat())) === FINAL_MAP_SHA256, 'Act 1 final map hash mismatch');

  const plate = extractAct1Rows(map);
  return { content: renderSnapshot(plate.rows, plate.sha256), plateSha256: plate.sha256 };
}

const args = process.argv.slice(2);
assert(args.length <= 1 && (args.length === 0 || args[0] === '--check'), 'usage: extract_act1_runtime_snapshot.mjs [--check]');
const generated = generateSnapshot();

if (args[0] === '--check') {
  assert(readFileSync(OUTPUT, 'utf8') === generated.content, 'checked-in Act 1 runtime snapshot is stale');
  console.log(`ACT 1 RUNTIME SNAPSHOT CHECK PASS: ${ACT1_WIDTH}x${ACT1_HEIGHT} ${generated.plateSha256}`);
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, generated.content);
  console.log(`ACT 1 RUNTIME SNAPSHOT WRITTEN: ${ACT1_WIDTH}x${ACT1_HEIGHT} ${generated.plateSha256}`);
}
